services:
  user_db:
    image: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=identity
      - POSTGRES_DB=identity
      - POSTGRES_PASSWORD=identity

  oauth:
    image: quay.io/keycloak/keycloak
    restart: always
    depends_on:
      - user_db
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://user_db/identity
      - KC_DB=postgres
      - KC_DB_USERNAME=identity
      - KC_DB_PASSWORD=identity
      - KC_HOSTNAME=localhost
    command: start-dev

volumes:
  pg_data:
